approve_by_comment: true
approve_regex: '^(Approved|:shipit:|:\+1:)'
reject_regex: '^(Rejected|:-1:)'
reset_on_push: false
author_approval: required
reviewers:
  members:
  - brantje
  - dschaper
  - jacobsalmela
  - Mcat12
  - PromoFaux
  name: pullapprove
  required: 3
