sudo: required
services:
  - docker
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt

script:
  # tox.ini handles setup, ordering of docker build first, and then run tests
  - tox
